server: 
    error: 
        include-exception: false
        include-stacktrace: never
    port: 8080
    servlet: 
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    compression: 
        enabled: true
        mime-types: text/html,text/plain,text/css,application/javascript,application/json
        min-response-size: 1024

spring: 
    datasource: 
        url: jdbc:mariadb://ezpro.duckdns.org:3306/geo?characterEncoding=UTF-8
        driver-class-name: org.mariadb.jdbc.Driver
        username: geo
        password: 1234

        hikari:
            connectionTimeout : 30000
            maximumPoolSize : 10
            maxLifetime : 1800000
            poolName : HikariCP
            readOnly : false
            connectionTestQuery : SELECT 1

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create
        properties: 
            hibernate: 
            show_sql: true

logging:
    level:
        org.hibernate.SQL: debug
